-- AlterTable
ALTER TABLE "public"."SummarySnapshot" ALTER COLUMN "dx" DROP NOT NULL,
ALTER COLUMN "keyConcern" DROP NOT NULL,
ALTER COLUMN "nextStep" DROP NOT NULL,
ALTER COLUMN "bodyPart" DROP NOT NULL;
